# Generated by Django 4.1.7 on 2023-02-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_item_title_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
